version: '3'
services:
    cryptocop-emails:
        build: ./cryptocop-emails
        container_name: cryptocop-emails
        networks:
            - "cryptocop-network"
    cryptocop.software.api:
        build: ./Cryptocop.Software.API
        container_name: cryptocop.software.api
        ports:
            - "7000:5001"
        networks:
            - "cryptocop-network"
    cryptocop-payments:
        build: ./cryptocop-payments
        container_name: cryptocop-payments
        networks:
            - "cryptocop-network"

networks:
    cryptocop-network:
        driver: bridge